# Generated by Django 5.2.6 on 2025-10-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp13', '0002_aboutsection_contactinfo_cv_homesection_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='homesection',
            old_name='description2',
            new_name='extra_desc',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='greeting',
            field=models.CharField(default="Hi, I'm", max_length=120),
        ),
        migrations.AddField(
            model_name='homesection',
            name='name',
            field=models.CharField(default='Ehsan', max_length=120),
        ),
        migrations.AddField(
            model_name='homesection',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='About Me', max_length=120),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(default='My Resume', max_length=120),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
