# Generated by Django 5.2.6 on 2025-10-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp13', '0003_alter_project_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Example: fa-brands fa-html5 or fa-brands fa-js', max_length=120, null=True),
        ),
    ]
