# Generated by Django 5.2.6 on 2025-10-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp13', '0004_alter_skill_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='twitter',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='e.g. +923001234567', max_length=20, null=True),
        ),
    ]
